In [163]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model

In [164]:
hiring = pd.read_csv("hiring.csv")

In [165]:
hiring

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [166]:
hiring.isna().sum()

experience                    2
test_score(out of 10)         1
interview_score(out of 10)    0
salary($)                     0
dtype: int64

In [167]:
hiring["experience"].fillna({0: "six", 1: "six"}, inplace = True)  #replacing the missing values in the experience column with their median

In [168]:
hiring["experience"].replace(to_replace = ["six", "six", "five", "two", "seven", "three", "ten", "eleven"], value = [6,6,5,2,7,3,10,11], inplace = True)

In [169]:
hiring

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           6                    8.0                           9      50000
1           6                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [170]:
median_value = hiring["test_score(out of 10)"].median() #replacing the missing values in the test_score column

In [171]:
hiring["test_score(out of 10)"].fillna(median_value, inplace = True)

In [183]:
hiring.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   experience                  8 non-null      int64  
 1   test_score(out of 10)       8 non-null      float64
 2   interview_score(out of 10)  8 non-null      int64  
 3   salary($)                   8 non-null      int64  
dtypes: float64(1), int64(3)
memory usage: 384.0 bytes


In [172]:
#split the data
features = hiring[["experience", "test_score(out of 10)", "interview_score(out of 10)"]]  #independent variables

In [173]:
features

experience  test_score(out of 10)  interview_score(out of 10)
0           6                    8.0                           9
1           6                    8.0                           6
2           5                    6.0                           7
3           2                   10.0                          10
4           7                    9.0                           6
5           3                    7.0                          10
6          10                    8.0                           7
7          11                    7.0                           8

In [174]:
targets = hiring[["salary($)"]]  #dependent variables

In [175]:
targets

salary($)
0      50000
1      45000
2      60000
3      65000
4      70000
5      62000
6      72000
7      80000

In [176]:
#fitting your data
reg = linear_model.LinearRegression()

In [184]:
reg.fit(features, targets)  #training the data

LinearRegression()

Question
This a hiring statics for a firm such as experience of candidate based on written test score and personal interview score. HR will decide the salary of the candidate. Given this data you need to build a machine learning model for the HR Department that will help them decide salaries for future candidates. Using this predict salariees for the following candidates:

a) 2 yrs experiences, 9 test score, 6 interview score
b) 12 yrs experiences, 10 test score, 10 interview score
c) 9 yrs experiences, 10 test score, 9 interview score
d) 24 yrs experiences, 4 test score, 3 interview score

In [179]:
reg.predict([[2,9,6]])

array([[47056.91056911]])

In [180]:
reg.predict([[12,10,10]])

array([[88227.64227642]])

In [181]:
reg.predict([[9,10,9]])

array([[76861.78861789]])

In [182]:
reg.predict([[24,4,3]])

array([[93495.93495935]])