### 1) Write a NumPy program to get help on the add function. 

In [2]:
import numpy as np
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

### 2) Write a NumPy program to create an array with values ranging from 12 to 38.


In [3]:
np.arange(12,39)

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37, 38])

### 3) Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.


In [4]:
arr = np.arange(2,11)
arr.reshape(3,3)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

### 4) Write a NumPy program to create a 2d array with 1 on the border and 0 inside.


In [5]:
n=5
border_array = np.ones((n, n), dtype=int)
border_array[1:-1, 1:-1] = 0
print(border_array)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


### 5) Write a NumPy program to append values to the end of an array.


In [6]:
import numpy as np
val = np.arange(0,11)
val
np.append(val, 55)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 55])

### 6) Write a NumPy program to generate five random numbers from the normal distribution.


In [7]:
np.random.randn(5)

array([ 0.09046568, -1.24421599,  0.05553317, -0.35050234,  1.28368003])